/**
 * dist-skills-drift.test.ts
 *
 * SW-036 integration tests for `scripts/check-dist-skills-drift.sh`.
 *
 * The guard asserts the compiled
 * `plugins/fusion-plugin-stelow/dist/skills.d.ts#STELOW_PLUGIN_VERSION` agrees
 * with `plugins/fusion-plugin-stelow/manifest.json#version` after
 * `npm run build`. The guard is the canonical SW-008 historical-miss detector
 * from `docs/agents-md-refs/post-mortems/v0.55.2-release-drift.md` §"Secondary
 * guard" (v0.55.0 shipped with `STELOW_PLUGIN_VERSION="0.54.3"` baked into
 * dist because the release commit skipped step 3 of the release workflow).
 *
 * Self-sufficiency strategy (SW-005/SW-007/SW-016 pattern):
 *   Each scenario builds its OWN tmpdir, copies the guard script into it,
 *   writes a fake `dist/skills.d.ts` + `manifest.json`, and exec's the
 *   script via the spawned node/bash pattern. The test does NOT depend on
 *   the actual repo's plugin files or run `npm run build` — it is fully
 *   deterministic against tmpdir fixtures.
 *
 * Scenarios covered:
 *   1. Pass: dist matches manifest (current state) → exit 0, OK message,
 *      no `::error::` annotations.
 *   2. Fail (stale dist): STELOW_PLUGIN_VERSION="0.54.3" vs manifest=0.55.2 →
 *      exit 1, `::error::` naming both versions and the re-bake command.
 *   3. Fail (missing dist): dist file absent → exit 1, `::error::` naming
 *      the missing file and the build:fusion-plugin re-bake command.
 *   4. Fail (SW-008 historical-miss): STELOW_PLUGIN_VERSION="0.54.3" vs
 *      manifest=0.55.0 → exit 1, full symptom reproduction of the
 *      v0.55.0 release-drift bug. This is the symptom-verification test
 *      named in the task PROMPT §"Symptom Verification".
 *
 * If any scenario fails, the SW-036 drift guard has regressed. Do NOT skip.
 */
import { afterEach, beforeAll, describe, expect, it } from 'vitest';
import { execFile } from 'node:child_process';
import { cp, mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const __filename = fileURLToPath(import.meta.url);
const __testDir = dirname(__filename);
const PROJECT_ROOT = join(__testDir, '..', '..');
const SCRIPT_PATH = join(PROJECT_ROOT, 'scripts', 'check-dist-skills-drift.sh');

// All tmpdirs created by this suite. afterEach removes them — never share a
// tmpdir across `it` blocks; each scenario owns its own root.
const tmpRoots: string[] = [];

afterEach(async () => {
  await Promise.all(
    tmpRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
  );
});

/**
 * Build a tmpdir that mirrors the repo layout the guard script inspects:
 *
 *   <root>/plugins/fusion-plugin-stelow/manifest.json     (canonical source)
 *   <root>/plugins/fusion-plugin-stelow/dist/skills.d.ts  (gitignored output)
 *   <root>/scripts/check-dist-skills-drift.sh             (copied from PROJECT_ROOT)
 *
 * Pass `distVersion: null` to OMIT the dist file (the missing-file scenario).
 *
 * Returns `{ workDir }` whose path is a clean tmpdir this fixture owns; the
 * caller exec's the script from there via execFile(..., { cwd: workDir }).
 */
type FixtureOpts = {
  distVersion: string | null;
  manifestVersion: string;
};

async function buildFixture(opts: FixtureOpts): Promise<{ workDir: string }> {
  const root = await mkdtemp(join(tmpdir(), 'stelow-sw036-'));
  tmpRoots.push(root);

  const pluginDir = join(root, 'plugins', 'fusion-plugin-stelow');
  await mkdir(pluginDir, { recursive: true });
  await mkdir(join(pluginDir, 'dist'), { recursive: true });

  // manifest.json — only `version` is read by the guard (via `node -p
  // require('./manifest.json').version`), but include `id` + `name` so the
  // JSON is shaped like a real Stelow manifest (proves the script reads only
  // `version` and tolerates extra fields).
  await writeFile(
    join(pluginDir, 'manifest.json'),
    JSON.stringify({
      id: 'fusion-plugin-stelow',
      name: 'Stelow',
      version: opts.manifestVersion,
    }),
  );

  if (opts.distVersion !== null) {
    // Match the exact shape `tsc -p plugins/fusion-plugin-stelow/tsconfig.json`
    // emits: `export declare const STELOW_PLUGIN_VERSION = "<v>";`. The guard's
    // regex anchors on this anchor so the fixture MUST emit the same shape;
    // a different shape (e.g., `export const STELOW_PLUGIN_VERSION = "<v>"`)
    // would test the wrong path.
    await writeFile(
      join(pluginDir, 'dist', 'skills.d.ts'),
      [
        '/** Generated by scripts/prepare-fusion-plugin.ts from canonical SKILL.md frontmatter. */',
        'import type { PluginSkillContribution } from \'./fusion-contract.js\';',
        'export declare const STELOW_SKILLS: PluginSkillContribution[];',
        'export declare const STELOW_PLUGIN_ID = "fusion-plugin-stelow";',
        `export declare const STELOW_PLUGIN_VERSION = "${opts.distVersion}";`,
        '',
      ].join('\n'),
    );
  }

  // Copy the guard into the tmpdir so it can run with `cwd: workDir`. The
  // script reads `${PWD}/${PLUGIN_DIR}/...`; the test must not rely on the
  // real repo's plugin tree.
  await mkdir(join(root, 'scripts'), { recursive: true });
  await cp(SCRIPT_PATH, join(root, 'scripts', 'check-dist-skills-drift.sh'));

  return { workDir: root };
}

/**
 * Invoke the guard script in `cwd` and capture exit status + stdout + stderr.
 * Never throws on non-zero exit; the caller's assertions inspect the raw
 * status so the script's actual emission shape drives the test.
 */
async function runGuard(workDir: string): Promise<{
  status: number | null;
  stdout: string;
  stderr: string;
}> {
  const child = execFile(
    'bash',
    ['scripts/check-dist-skills-drift.sh'],
    { cwd: workDir },
  );
  let stdout = '';
  let stderr = '';
  child.stdout?.on('data', (chunk: Buffer | string) => {
    stdout += chunk.toString();
  });
  child.stderr?.on('data', (chunk: Buffer | string) => {
    stderr += chunk.toString();
  });
  const { status } = await new Promise<{ status: number | null }>((resolve, reject) => {
    child.on('error', reject);
    child.on('close', (code) => resolve({ status: code }));
  });
  return { status, stdout, stderr };
}

describe('SW-036: scripts/check-dist-skills-drift.sh', () => {
  beforeAll(() => {
    // Sanity: the script MUST exist in PROJECT_ROOT (the CI wires it as
    // `bash scripts/check-dist-skills-drift.sh`). Fail-fast if it ever
    // gets removed by mistake — subsequent scenarios would otherwise all
    // fail with a misleading "script missing" diagnostic.
    expect(
      SCRIPT_PATH,
      'scripts/check-dist-skills-drift.sh must exist for SW-036 to have any meaning',
    ).toContain('scripts/check-dist-skills-drift.sh');
  });

  it('scenario 1 (pass): dist=0.55.2 matches manifest=0.55.2 → exit 0 with OK, no ::error::', async () => {
    // The current repo state: src/skills.ts + manifest.json both at 0.55.2,
    // freshly-built dist matches both.
    const { workDir } = await buildFixture({
      distVersion: '0.55.2',
      manifestVersion: '0.55.2',
    });

    const start = Date.now();
    const { status, stdout, stderr } = await runGuard(workDir);
    const elapsedMs = Date.now() - start;

    expect(status).toBe(0);
    expect(elapsedMs, 'guard should complete in well under 1s for a tiny fixture').toBeLessThan(1000);
    expect(stdout).toContain('OK:');
    expect(stdout).toContain('0.55.2');
    expect(stdout).toContain('plugins/fusion-plugin-stelow/dist/skills.d.ts');
    expect(stdout).toContain('plugins/fusion-plugin-stelow/manifest.json');
    expect(stdout, 'pass case must NOT emit any ::error:: annotations').not.toContain('::error::');
    expect(stderr, 'pass case must emit empty stderr').toBe('');
  });

  it('scenario 2 (stale dist): dist=0.54.3 vs manifest=0.55.2 → exit 1 with ::error:: naming both versions + re-bake command', async () => {
    const { workDir } = await buildFixture({
      distVersion: '0.54.3',
      manifestVersion: '0.55.2',
    });
    const { status, stdout, stderr } = await runGuard(workDir);
    const combined = stdout + stderr;

    expect(status).toBe(1);
    // Both sides of the drift must be named explicitly so the engineer can
    // act without re-running the script.
    expect(combined).toContain('0.54.3');
    expect(combined).toContain('0.55.2');
    // GitHub Actions annotation prefix.
    expect(combined).toContain('::error::');
    // File paths the engineer needs to look at.
    expect(combined).toContain('plugins/fusion-plugin-stelow/dist/skills.d.ts');
    expect(combined).toContain('plugins/fusion-plugin-stelow/manifest.json');
    // The const the guard inspects.
    expect(combined).toContain('STELOW_PLUGIN_VERSION');
    // The re-bake command is the canonical fix from AGENTS.md §"Versioning"
    // step 3 — guarding only with `matches` rather than `toContain` ensures
    // the test reads as "this command must appear" rather than "any substring".
    expect(combined).toMatch(/npm run prepare:fusion-plugin && npm run build:fusion-plugin/);
    // The pass-only "OK:" line must NOT appear on drift.
    expect(stdout, 'drift case must NOT emit OK:').not.toMatch(/^OK:/m);
  });

  it('scenario 3 (missing dist): dist absent + manifest=0.55.2 → exit 1 with ::error:: naming missing file', async () => {
    const { workDir } = await buildFixture({
      distVersion: null,
      manifestVersion: '0.55.2',
    });
    const { status, stdout, stderr } = await runGuard(workDir);
    const combined = stdout + stderr;

    expect(status).toBe(1);
    expect(combined).toContain('::error::');
    expect(combined).toContain('does not exist');
    expect(combined).toContain('plugins/fusion-plugin-stelow/dist/skills.d.ts');
    // The missing-file branch instructs a different re-bake (just
    // `build:fusion-plugin`, not the full prepare+build), because the build
    // must have run to even reach this check. Make sure it mentions the
    // correct fix and NOT the drift re-bake command from scenario 2.
    expect(combined).toMatch(/npm run build:fusion-plugin/);
    expect(combined).not.toMatch(/STELOW_PLUGIN_VERSION \(.*\) does not match/);
    // Drift-specific error must NOT fire when the artifact is absent — the
    // missing-file check takes priority.
    expect(stdout, 'missing-file case must NOT emit OK:').not.toMatch(/^OK:/m);
  });

  it('scenario 4 (SW-008 historical-miss symptom reproduction): dist=0.54.3 vs manifest=0.55.0 → exit 1, exact reproduction of the v0.55.0 release-drift bug', async () => {
    // This is the symptom-reproduction test named in the PROMPT §"Symptom
    // Verification": write a stale dist + current manifest and assert the
    // guard fires the v0.55.0 historical-miss pattern. If this scenario
    // ever passes silently (exit 0), the guard has regressed and the
    // engineer's `0.54.3` observation at msg-ce305ab5 will not be
    // catchable in CI.
    const { workDir } = await buildFixture({
      distVersion: '0.54.3',
      manifestVersion: '0.55.0',
    });
    const { status, stdout, stderr } = await runGuard(workDir);
    const combined = stdout + stderr;

    expect(status).toBe(1);
    // The two specific version strings from the historical bug.
    expect(combined).toContain('0.54.3');
    expect(combined).toContain('0.55.0');
    expect(combined).toContain('::error::');
    expect(combined).toContain('does not match');
    // The re-bake instruction.
    expect(combined).toMatch(/npm run prepare:fusion-plugin && npm run build:fusion-plugin/);
    // Explicit anchor on STELOW_PLUGIN_VERSION (not just any quoted version
    // string) — guards against a future regex regression that drops the
    // const-name anchor.
    expect(combined).toContain('STELOW_PLUGIN_VERSION');
    expect(stdout).not.toMatch(/^OK:/m);
  });
});

describe('SW-036: guard reads manifest version via Node, tolerates extra fields', () => {
  // The guard uses `node -p "require('./manifest.json').version"`. If the
  // manifest ever grows sibling fields (it already does — `id`, `name`,
  // `skills[]`, `settingsSchema`), the guard MUST still read `version` and
  // not choke on the extra fields. The fixture helper already includes
  // `id` and `name`; this scenario exercises a fuller manifest to lock the
  // field-extraction contract.

  it('passes when manifest carries version + sibling fields, dist matches version', async () => {
    const root = await mkdtemp(join(tmpdir(), 'stelow-sw036-overdetailed-'));
    tmpRoots.push(root);
    const pluginDir = join(root, 'plugins', 'fusion-plugin-stelow');
    await mkdir(pluginDir, { recursive: true });
    await mkdir(join(pluginDir, 'dist'), { recursive: true });
    await writeFile(
      join(pluginDir, 'manifest.json'),
      JSON.stringify({
        id: 'fusion-plugin-stelow',
        name: 'Stelow',
        version: '0.55.2',
        description: 'Stelow product-planning workflow and skills for Fusion.',
        author: 'calionauta',
        fusionVersion: '>=0.1.0',
        skills: [{ skillId: 'stelow-adapter-cli', name: 'stelow-adapter-cli' }],
        settingsSchema: { installProjectIntegration: { type: 'boolean', defaultValue: true } },
      }),
    );
    await writeFile(
      join(pluginDir, 'dist', 'skills.d.ts'),
      [
        'import type { PluginSkillContribution } from \'./fusion-contract.js\';',
        'export declare const STELOW_SKILLS: PluginSkillContribution[];',
        'export declare const STELOW_PLUGIN_ID = "fusion-plugin-stelow";',
        'export declare const STELOW_PLUGIN_VERSION = "0.55.2";',
        '',
      ].join('\n'),
    );
    await mkdir(join(root, 'scripts'), { recursive: true });
    await cp(SCRIPT_PATH, join(root, 'scripts', 'check-dist-skills-drift.sh'));

    const { status, stdout, stderr } = await runGuard(root);
    expect(status).toBe(0);
    expect(stdout).toContain('OK:');
    expect(stdout).toContain('0.55.2');
    expect(stderr).toBe('');
  });
});
