import { cp, mkdir, mkdtemp, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { parse as parseYaml } from 'yaml';

import {
  STELOW_PLUGIN_ID,
  buildFusionSettings,
  buildFusionWorkflowIR,
  stableStringify,
  validateFusionSettings,
  validateFusionWorkflowIR,
} from '../extensions/stelow/adapters/commands/fusion-artifacts.js';

interface PreparedSkill {
  skillId: string;
  name: string;
  description: string;
}

export interface PrepareFusionPluginOptions {
  repoRoot?: string;
  pluginDir?: string;
}

async function pathExists(path: string): Promise<boolean> {
  try { await readdir(path); return true; } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOTDIR') {
      try { await readFile(path); return true; } catch { return false; }
    }
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false;
    throw error;
  }
}

function readSkillFrontmatter(body: string, directory: string): PreparedSkill {
  const match = body.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!match) throw new Error(`invalid skill frontmatter: ${directory}/SKILL.md`);
  const frontmatter = parseYaml(match[1]) as { name?: unknown; description?: unknown };
  if (typeof frontmatter.name !== 'string' || frontmatter.name.trim() !== directory) {
    throw new Error(`skill frontmatter name must equal directory '${directory}'`);
  }
  if (typeof frontmatter.description !== 'string' || frontmatter.description.trim().length === 0) {
    throw new Error(`skill description must be non-empty: ${directory}/SKILL.md`);
  }
  return { skillId: directory, name: directory, description: frontmatter.description.trim() };
}

async function discoverSkills(sourceRoot: string): Promise<PreparedSkill[]> {
  const entries = (await readdir(sourceRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory() && entry.name.startsWith('stelow-product-'))
    .sort((left, right) => left.name.localeCompare(right.name));
  if (entries.length === 0) throw new Error(`no stelow-product-* skills found in ${sourceRoot}`);
  const skills = await Promise.all(entries.map(async ({ name }) =>
    readSkillFrontmatter(await readFile(join(sourceRoot, name, 'SKILL.md'), 'utf8'), name)));
  const names = new Set<string>();
  for (const skill of skills) {
    if (names.has(skill.name)) throw new Error(`duplicate skill name: ${skill.name}`);
    names.add(skill.name);
  }
  return skills;
}

function renderSkillsSource(skills: PreparedSkill[], version: string): string {
  const rows = skills.map((skill) => `  ${JSON.stringify({
    ...skill,
    skillFiles: [`skills/${skill.skillId}/SKILL.md`],
  })},`).join('\n');
  return `/** Generated by scripts/prepare-fusion-plugin.ts from canonical SKILL.md frontmatter. */\nimport type { PluginSkillContribution } from './fusion-contract.js';\n\nexport const STELOW_SKILLS: PluginSkillContribution[] = [\n${rows}\n];\n\nexport const STELOW_PLUGIN_ID = 'fusion-plugin-stelow';\nexport const STELOW_PLUGIN_VERSION = ${JSON.stringify(version)};\n`;
}

async function replaceAtomically(
  pluginDir: string,
  stagedRoot: string,
  relativeTargets: string[],
): Promise<void> {
  const token = `${process.pid}-${Date.now()}`;
  const backups: Array<{ target: string; backup: string; existed: boolean }> = [];
  try {
    for (const relativeTarget of relativeTargets) {
      const target = join(pluginDir, relativeTarget);
      const staged = join(stagedRoot, relativeTarget);
      const backup = `${target}.${token}.bak`;
      const existed = await pathExists(target);
      if (existed) await rename(target, backup);
      backups.push({ target, backup, existed });
      await mkdir(dirname(target), { recursive: true });
      await rename(staged, target);
    }
  } catch (error) {
    for (const { target, backup, existed } of backups.reverse()) {
      await rm(target, { recursive: true, force: true }).catch(() => {});
      if (existed) await rename(backup, target).catch(() => {});
    }
    throw error;
  } finally {
    await Promise.all(backups.map(({ backup }) => rm(backup, { recursive: true, force: true }).catch(() => {})));
  }
}

export async function prepareFusionPlugin(options: PrepareFusionPluginOptions = {}): Promise<number> {
  const repoRoot = resolve(options.repoRoot ?? process.cwd());
  const pluginDir = resolve(options.pluginDir ?? join(repoRoot, 'plugins', 'fusion-plugin-stelow'));
  const sourceSkills = join(repoRoot, 'skills');

  // Build, serialize, parse, and validate every source before the first final-path write.
  const skills = await discoverSkills(sourceSkills);
  const settingsBytes = stableStringify(buildFusionSettings(repoRoot));
  const workflowBytes = stableStringify(buildFusionWorkflowIR(repoRoot));
  const settings = JSON.parse(settingsBytes) as unknown;
  const workflow = JSON.parse(workflowBytes) as unknown;
  const settingsCheck = validateFusionSettings(settings);
  if (!settingsCheck.ok) throw new Error(`invalid generated settings: ${settingsCheck.error}`);
  const workflowCheck = validateFusionWorkflowIR(workflow);
  if (!workflowCheck.ok) throw new Error(`invalid generated workflow: ${workflowCheck.error}`);

  const packageMetadata = JSON.parse(await readFile(join(repoRoot, 'package.json'), 'utf8')) as { version: string };
  const manifest = JSON.parse(await readFile(join(pluginDir, 'manifest.json'), 'utf8')) as Record<string, unknown>;
  if (manifest.id !== STELOW_PLUGIN_ID) throw new Error(`manifest id mismatch: expected ${STELOW_PLUGIN_ID}`);
  manifest.version = packageMetadata.version;
  manifest.skills = skills.map(({ skillId, name }) => ({ skillId, name }));

  const stage = await mkdtemp(join(dirname(pluginDir), '.fusion-plugin-stelow-stage-'));
  try {
    await mkdir(join(stage, 'skills'), { recursive: true });
    await Promise.all(skills.map(({ skillId }) =>
      cp(join(sourceSkills, skillId), join(stage, 'skills', skillId), { recursive: true })));
    await mkdir(join(stage, 'artifacts', 'workflows'), { recursive: true });
    await mkdir(join(stage, 'src'), { recursive: true });
    await writeFile(join(stage, 'artifacts', 'settings.json'), settingsBytes, 'utf8');
    await writeFile(join(stage, 'artifacts', 'workflows', 'stelow-v2.json'), workflowBytes, 'utf8');
    await writeFile(join(stage, 'manifest.json'), stableStringify(manifest), 'utf8');
    await writeFile(join(stage, 'src', 'skills.ts'), renderSkillsSource(skills, packageMetadata.version), 'utf8');
    await replaceAtomically(pluginDir, stage, ['skills', 'artifacts', 'manifest.json', join('src', 'skills.ts')]);
  } finally {
    await rm(stage, { recursive: true, force: true });
  }
  return skills.length;
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : '';
if (import.meta.url === invokedPath) {
  prepareFusionPlugin()
    .then((count) => process.stdout.write(`Stelow Fusion plugin prepared: ${count} skills and validated artifacts.\n`))
    .catch((error: unknown) => {
      process.stderr.write(`prepare-fusion-plugin failed: ${error instanceof Error ? error.message : String(error)}\n`);
      process.exitCode = 1;
    });
}
